export const ADD_BAGS = 'ADD_BAGS';
export const FETCH_BAGS = 'FETCH_BAGS';
export const ERROR_BAGS = 'ERROR_BAGS';
export const CHANGE_BAGS_LIST_TOTAL_SIZE = 'CHANGE_BAGS_LIST_TOTAL_SIZE';
export const CHANGE_CURRENT_PAGE = 'CHANGE_CURRENT_PAGE';
export const CHANGE_PAGE_SIZE = 'CHANGE_PAGE_SIZE';

export const ADD_BAGS_SAGA = 'ADD_BAGS_SAGA';