export const ADD_PRICE_FILTER_ATRIBUTES = 'ADD_PRICE_FILTER_ATRIBUTES';
export const ADD_BRAND_FILTER_ATRIBUTES = 'ADD_BRAND_FILTER_ATRIBUTES';
export const START_ADDING_FILTER = 'START_ADDING_FILTER';
export const ADD_FILTERS_SAGA = 'ADD_FILTERS_SAGA';
export const ADD_FILTERS = 'ADD_FILTERS'; 
export const SET_MIN_PRICE = 'SET_MIN_PRICE';
export const SET_MAX_PRICE = 'SET_MAX_PRICE';