export const ADD_PRICE_FILTER_ATRIBUTES = 'ADD_PRICE_FILTER_ATRIBUTES';
export const ADD_BRAND_FILTER_ATRIBUTES = 'ADD_BRAND_FILTER_ATRIBUTES';
export const ADD_FILTERS_SAGA = 'ADD_FILTERS_SAGA';
export const ADD_FILTERS = 'ADD_FILTERS'; 